name: LALALA

on:
  push:
    branches:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "BUILD"

  upload:
    needs: build
    if: |
      github.ref == 'refs/heads/master'
        || github.ref == 'refs/heads/release*'
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "UPLOAD"