name: LALALA

on:
  push:
    branches:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    envs: 
      IS_RELEASE: ${{startsWith(github.ref, "refs/heads/release")}}

    steps:
      - name: Echo
        run: echo "BUILD"
      - name: CHECKS
        run: |
          echo github.ref
          echo github.ref == 'refs/heads/release*'
          echo ${{github.ref}} == 'refs/heads/release*'
          echo ${{github.ref == 'refs/heads/release*'}}
          echo ${{github.ref == 'refs/heads/master'}} || ${{github.ref == 'refs/heads/release*'}}
          echo github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release*'
          echo ${{github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release*'}}
          echo $IS_RELEASE

  upload:
    needs: build
    if: |
      ${{github.ref == 'refs/heads/master'}} || ${{github.ref == 'refs/heads/release*'}}
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "UPLOAD"